"""
Generates the synthetic VGM corpus using MusicGen and writes audio files +
a manifest to the Modal Volume `flowing-trails-corpus`.

Prerequisites:
  - `corpus_prompts.json` generated by `generate_corpus_prompts.py`
  - Modal Volume `flowing-trails-corpus` exists (created automatically on first run)
  - Modal CLI authenticated (`modal token new`)

Usage:
    modal run retrieval/generate_corpus.py

The manifest written to the Volume (corpus_manifest.json) is the input
for the CLAP indexing job (retrieval/embed_corpus.py + retrieval/index_corpus.py).
"""

import json
import modal
from pathlib import Path
from config import (
    VOLUME_NAME,
    VOLUME_MOUNT_PATH,
    MODAL_SECRET_NAME,
    MUSICGEN_BASE_MODEL,
    GPU_CONFIG,
    CORPUS_AUDIO_SAMPLE_RATE,
)

app = modal.App("flowing-trails-corpus-gen")

volume = modal.Volume.from_name(VOLUME_NAME, create_if_missing=True)

image = (
    modal.Image.debian_slim(python_version="3.11")
    .apt_install(
        "pkg-config",
        "ffmpeg",
        "libavformat-dev",
        "libavcodec-dev",
        "libavdevice-dev",
        "libavutil-dev",
        "libswscale-dev",
        "libswresample-dev",
        "libavfilter-dev",
    )
    .pip_install(
        "numpy<2",  # pin before torch — compiled torch 2.x extensions require numpy 1.x ABI
        "torch>=2.4.0",  # 2.4+ required by transformers; audiocraft accepts >=2.1.0
        "torchaudio>=2.4.0",
        "transformers>=4.40.0",
        "audiocraft",
        "soundfile",
    )
    .add_local_python_source("config")
)


@app.function(
    gpu=GPU_CONFIG,
    image=image,
    volumes={VOLUME_MOUNT_PATH: volume},
    secrets=[modal.Secret.from_name(MODAL_SECRET_NAME)],
    timeout=3600,
)
def generate_corpus(prompts: list[dict]) -> dict:
    import functools
    import logging

    import soundfile as sf
    import torch

    # audiocraft checkpoints use omegaconf globals that torch 2.6+ rejects
    # under weights_only=True — patch for Meta's own trusted checkpoints.
    _original_load = torch.load
    torch.load = functools.partial(_original_load, weights_only=False)
    from audiocraft.models import MusicGen  # type: ignore

    # stdlib logging — structlog isn't in the Modal container image
    logging.basicConfig(
        level=logging.INFO, format="%(levelname)s | %(name)s | %(message)s"
    )
    log = logging.getLogger("flowing-trails.corpus-gen")

    model = MusicGen.get_pretrained(MUSICGEN_BASE_MODEL)
    torch.load = _original_load

    manifest = []
    failed = []

    for item in prompts:
        clip_id = item["id"]
        try:
            model.set_generation_params(duration=item["duration_seconds"])
            output = model.generate([item["prompt"]])  # shape: [1, channels, samples]

            # MusicGen outputs at 32kHz — save as-is; CLAP indexing resamples to 48kHz
            filename = f"{clip_id}.wav"
            audio_path = f"/corpus/{filename}"
            # output[0] shape is [channels, samples] — soundfile expects [samples, channels]
            audio_np = output[0].cpu().numpy().T
            sf.write(
                audio_path,
                audio_np,
                samplerate=CORPUS_AUDIO_SAMPLE_RATE,
                subtype="PCM_16",
            )

            manifest.append({**item, "corpus_file_path": filename})
            log.info("Generated %s", clip_id)

        except Exception as e:
            log.error("Failed %s: %s", clip_id, e)
            failed.append({"id": clip_id, "error": str(e)})

    with open("/corpus/corpus_manifest.json", "w") as f:
        json.dump(manifest, f, indent=2)

    volume.commit()

    result = {"generated": len(manifest), "failed": len(failed)}
    if failed:
        result["failed_ids"] = [f["id"] for f in failed]
    return result


@app.local_entrypoint()
def main():
    import sys

    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
    from otel_utils import get_logger, setup_logging

    setup_logging()
    log = get_logger("corpus-gen")

    prompts_path = Path(__file__).parent / "corpus_prompts.json"
    if not prompts_path.exists():
        raise FileNotFoundError(
            f"{prompts_path} not found. "
            "Run `python retrieval/generate_corpus_prompts.py` first."
        )

    with open(prompts_path) as f:
        prompts = json.load(f)

    log.info("Submitting prompts to Modal", count=len(prompts))
    result = generate_corpus.remote(prompts)
    log.info(
        "Generation complete",
        generated=result["generated"],
        failed=result["failed"],
    )
    if result.get("failed_ids"):
        log.warning("Failed clip IDs", ids=result["failed_ids"])
